Traceback (most recent call last):
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sys
import re
import pickle
from janome.tokenizer import Tokenizer
import numpy as np
import collections

with open("/Users/ryozawau/css_nlp/notebook/Data/dokujo-tsushin.txt", mode="r",encoding="utf-8") as f: # Ê≥®1Ôºâ
    original_corpus = f.readlines()

text = re.sub("http://news.livedoor.com/article/detail/[0-9]{7}/","", original_corpus) # Ê≥®2Ôºâ
text = re.sub("[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\+[0-9]{4}","", text) # Ê≥®3Ôºâ
text = re.sub("[\f\n\r\t\v]","", text)
text = re.sub("„ÄÄ","", text)
text = re.sub("[„Äå„Äç]","", text)
text = [re.sub("[ÔºàÔºâ]","", text)]

# Ôºú„Éù„Ç§„É≥„ÉàÔºû
t = Tokenizer()

words_list = []
for word in text:
    words_list.append(t.tokenize(word, wakati=True))

------------------

----- stderr -----
<>:12: SyntaxWarning: invalid escape sequence '\+'
<>:12: SyntaxWarning: invalid escape sequence '\+'
/var/folders/0s/grknnvt93bs7w2rbrt894wkc0000gn/T/ipykernel_14267/226934965.py:12: SyntaxWarning: invalid escape sequence '\+'
  text = re.sub("[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\+[0-9]{4}","", text) # Ê≥®3Ôºâ
/var/folders/0s/grknnvt93bs7w2rbrt894wkc0000gn/T/ipykernel_14267/226934965.py:12: SyntaxWarning: invalid escape sequence '\+'
  text = re.sub("[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\+[0-9]{4}","", text) # Ê≥®3Ôºâ
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 4[0m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mre[39;00m
[1;32m      3[0m [38;5;28;01mimport[39;00m [38;5;21;01mpickle[39;00m
[0;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjanome[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtokenizer[39;00m [38;5;28;01mimport[39;00m Tokenizer
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mcollections[39;00m

[0;31mModuleNotFoundError[0m: No module named 'janome'

