Traceback (most recent call last):
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/ryozawau/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 共起行列を作成
C = create_co_matrix(corpus, vocab_size, window_size=1)
print(C)

W = ppmi(C, verbose=True)


# 正の相互情報量行列
print(np.round(W, 2))
------------------

----- stdout -----
[[0 1 0 0 0 0 0]
 [1 0 1 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0]
 [0 1 0 0 0 0 1]
 [0 0 0 0 0 1 0]]
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[26], line 5[0m
[1;32m      2[0m C [38;5;241m=[39m create_co_matrix(corpus, vocab_size, window_size[38;5;241m=[39m[38;5;241m1[39m)
[1;32m      3[0m [38;5;28mprint[39m(C)
[0;32m----> 5[0m W [38;5;241m=[39m [43mppmi[49m[43m([49m[43mC[49m[43m,[49m[43m [49m[43mverbose[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m      8[0m [38;5;66;03m# 正の相互情報量行列[39;00m
[1;32m      9[0m [38;5;28mprint[39m(np[38;5;241m.[39mround(W, [38;5;241m2[39m))

Cell [0;32mIn[25], line 17[0m, in [0;36mppmi[0;34m(C, verbose, eps)[0m
[1;32m     14[0m cnt [38;5;241m=[39m [38;5;241m0[39m [38;5;66;03m# 処理回数を初期化[39;00m
[1;32m     16[0m [38;5;66;03m# 1語ずつ正の相互情報量を計算[39;00m
[0;32m---> 17[0m [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [43mtqdm[49m[43m([49m[38;5;28;43mrange[39;49m[43m([49m[43mC[49m[38;5;241;43m.[39;49m[43mshape[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m[43m)[49m: [38;5;66;03m# 各行[39;00m
[1;32m     18[0m     [38;5;28;01mfor[39;00m j [38;5;129;01min[39;00m [38;5;28mrange[39m(C[38;5;241m.[39mshape[[38;5;241m1[39m]): [38;5;66;03m# 各列[39;00m
[1;32m     19[0m         
[1;32m     20[0m         [38;5;66;03m# PPMIを計算[39;00m
[1;32m     21[0m         pmi [38;5;241m=[39m np[38;5;241m.[39mlog2(C[i, j] [38;5;241m*[39m N [38;5;241m/[39m (S[j] [38;5;241m*[39m S[i]) [38;5;241m+[39m eps)

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/tqdm/notebook.py:233[0m, in [0;36mtqdm_notebook.__init__[0;34m(self, *args, **kwargs)[0m
[1;32m    231[0m unit_scale [38;5;241m=[39m [38;5;241m1[39m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39munit_scale [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39munit_scale [38;5;129;01mor[39;00m [38;5;241m1[39m
[1;32m    232[0m total [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mtotal [38;5;241m*[39m unit_scale [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mtotal [38;5;28;01melse[39;00m [38;5;28mself[39m[38;5;241m.[39mtotal
[0;32m--> 233[0m [38;5;28mself[39m[38;5;241m.[39mcontainer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mstatus_printer[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mfp[49m[43m,[49m[43m [49m[43mtotal[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdesc[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mncols[49m[43m)[49m
[1;32m    234[0m [38;5;28mself[39m[38;5;241m.[39mcontainer[38;5;241m.[39mpbar [38;5;241m=[39m proxy([38;5;28mself[39m)
[1;32m    235[0m [38;5;28mself[39m[38;5;241m.[39mdisplayed [38;5;241m=[39m [38;5;28;01mFalse[39;00m

File [0;32m~/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/tqdm/notebook.py:108[0m, in [0;36mtqdm_notebook.status_printer[0;34m(_, total, desc, ncols)[0m
[1;32m     99[0m [38;5;66;03m# Fallback to text bar if there's no total[39;00m
[1;32m    100[0m [38;5;66;03m# DEPRECATED: replaced with an 'info' style bar[39;00m
[1;32m    101[0m [38;5;66;03m# if not total:[39;00m
[0;32m   (...)[0m
[1;32m    105[0m 
[1;32m    106[0m [38;5;66;03m# Prepare IPython progress bar[39;00m
[1;32m    107[0m [38;5;28;01mif[39;00m IProgress [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:  [38;5;66;03m# #187 #451 #558 #872[39;00m
[0;32m--> 108[0m     [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(WARN_NOIPYW)
[1;32m    109[0m [38;5;28;01mif[39;00m total:
[1;32m    110[0m     pbar [38;5;241m=[39m IProgress([38;5;28mmin[39m[38;5;241m=[39m[38;5;241m0[39m, [38;5;28mmax[39m[38;5;241m=[39mtotal)

[0;31mImportError[0m: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

